# Introduction to pytorch

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.1.1+cu121


In [4]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [5]:
scaler.ndim

0

In [6]:
scaler.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[6, 7],
                       [8, 9]])


In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[0]

tensor([6, 7])

In [14]:
MATRIX[1]

tensor([8, 9])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

In [19]:
TENSOR[0][1]

tensor([3, 4, 5])

In [20]:
TENSOR[0][1][1]

tensor(4)

## Random tensor

In [21]:
random_tensor = torch.rand(3,4) 
random_tensor

tensor([[0.4136, 0.8317, 0.8100, 0.2342],
        [0.3056, 0.4711, 0.6434, 0.1069],
        [0.4974, 0.9584, 0.9175, 0.2795]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor = torch.rand(1, 10,10) 
random_tensor

tensor([[[0.0259, 0.9240, 0.8894, 0.8615, 0.3485, 0.7770, 0.7605, 0.0912,
          0.8825, 0.9968],
         [0.8439, 0.9368, 0.2466, 0.0624, 0.1661, 0.5086, 0.6222, 0.9654,
          0.7391, 0.5583],
         [0.1947, 0.3275, 0.3919, 0.8947, 0.1595, 0.8586, 0.5031, 0.0693,
          0.9685, 0.8229],
         [0.5211, 0.2393, 0.1965, 0.3153, 0.2382, 0.3689, 0.5072, 0.3150,
          0.0256, 0.4389],
         [0.5986, 0.8072, 0.3025, 0.9006, 0.0501, 0.9381, 0.4409, 0.9151,
          0.1355, 0.0287],
         [0.7805, 0.1438, 0.0277, 0.4889, 0.4880, 0.6090, 0.5192, 0.1205,
          0.5509, 0.8858],
         [0.6132, 0.9460, 0.1699, 0.7664, 0.0121, 0.5402, 0.5846, 0.6092,
          0.7515, 0.1606],
         [0.3445, 0.0496, 0.6624, 0.7824, 0.4967, 0.0704, 0.3259, 0.1400,
          0.0770, 0.0718],
         [0.7189, 0.5044, 0.0350, 0.3379, 0.9718, 0.7478, 0.2271, 0.7976,
          0.6812, 0.6932],
         [0.8238, 0.5082, 0.0666, 0.0839, 0.1611, 0.4587, 0.8873, 0.2440,
          0.6895,

In [24]:
random_tensor.ndim

3

In [25]:
# create a random tensor with similar shape of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor

tensor([[[0.5080, 0.4279, 0.8866],
         [0.3827, 0.7236, 0.1101],
         [0.5506, 0.0038, 0.5631],
         ...,
         [0.1989, 0.6847, 0.0447],
         [0.1590, 0.9091, 0.4693],
         [0.1722, 0.9684, 0.7078]],

        [[0.1857, 0.1013, 0.4615],
         [0.5032, 0.2991, 0.9636],
         [0.7039, 0.3554, 0.3849],
         ...,
         [0.2514, 0.5260, 0.5160],
         [0.2763, 0.9554, 0.0049],
         [0.1272, 0.1795, 0.1911]],

        [[0.5233, 0.0798, 0.6682],
         [0.4120, 0.1972, 0.2557],
         [0.9588, 0.5852, 0.6871],
         ...,
         [0.2479, 0.4228, 0.8191],
         [0.8805, 0.7590, 0.4558],
         [0.8466, 0.6995, 0.2262]],

        ...,

        [[0.8756, 0.6762, 0.8820],
         [0.0851, 0.7973, 0.5498],
         [0.8329, 0.9816, 0.8320],
         ...,
         [0.9948, 0.9996, 0.6097],
         [0.3239, 0.3046, 0.9549],
         [0.7402, 0.6143, 0.8637]],

        [[0.3818, 0.7167, 0.7522],
         [0.8936, 0.8112, 0.5023],
         [0.

In [26]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [27]:
random_image_size_tensor.ndim

3

### zeros and ones

In [28]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [29]:
onse = torch.ones(2, 3)
onse

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [30]:
onse.dtype

torch.float32

## creating a range of tensors and tensors-like

In [31]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [33]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**note:** tensor data types is one of the 3 big errors you'll run into with pytorch & deep learnig:
1. tensors not right data types
2. tensors not right shape
3. tensors not on the right device

In [34]:
torch.tensor([3.0, 6.0, 9.0]).dtype

torch.float32

In [35]:
torch.tensor([3.0, 6.0, 9.0], dtype=None).dtype

torch.float32

In [36]:
torch.tensor([3.0, 6.0, 9.0],
             dtype=None, # what data type is the tensor (float32 or float16)
             device=None, # what device is your tenosr on 
             requires_grad=False # whether or not to track gradients with this tensors operations 
            )

tensor([3., 6., 9.])

In [37]:
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

## getting infromation about tenosrs (tensor attributes)
1. to get date type of a tensor, use `tensor.dtype`
2. to get shape from a tensor, use `tensor.shape`
3. to get device from a tensor, use `tensor.device`

In [38]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9522, 0.0091, 0.0723, 0.0204],
        [0.5692, 0.5209, 0.2219, 0.9780],
        [0.7116, 0.9252, 0.9608, 0.0926]])

In [39]:
print(some_tensor)
print(f"data type of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.9522, 0.0091, 0.0723, 0.0204],
        [0.5692, 0.5209, 0.2219, 0.9780],
        [0.7116, 0.9252, 0.9608, 0.0926]])
data type of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


In [40]:
some_tensor + 10

tensor([[10.9522, 10.0091, 10.0723, 10.0204],
        [10.5692, 10.5209, 10.2219, 10.9780],
        [10.7116, 10.9252, 10.9608, 10.0926]])

In [41]:
some_tensor ** 2

tensor([[9.0663e-01, 8.2729e-05, 5.2296e-03, 4.1532e-04],
        [3.2404e-01, 2.7132e-01, 4.9250e-02, 9.5651e-01],
        [5.0637e-01, 8.5608e-01, 9.2309e-01, 8.5695e-03]])

In [42]:
some_tensor / 10

tensor([[0.0952, 0.0009, 0.0072, 0.0020],
        [0.0569, 0.0521, 0.0222, 0.0978],
        [0.0712, 0.0925, 0.0961, 0.0093]])

In [43]:
8/3

2.6666666666666665

In [44]:
8//3

2

## manupaltin tesnors

tensors operatons include:
* Adding
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multipliciton

In [45]:
some_tensor = some_tensor + 5
some_tensor

tensor([[5.9522, 5.0091, 5.0723, 5.0204],
        [5.5692, 5.5209, 5.2219, 5.9780],
        [5.7116, 5.9252, 5.9608, 5.0926]])

In [46]:
some_tensor = some_tensor * 5
some_tensor

tensor([[29.7609, 25.0455, 25.3616, 25.1019],
        [27.8462, 27.6044, 26.1096, 29.8901],
        [28.5580, 29.6262, 29.8039, 25.4629]])

In [47]:
some_tensor = some_tensor - 5
some_tensor

tensor([[24.7609, 20.0455, 20.3616, 20.1019],
        [22.8462, 22.6044, 21.1096, 24.8901],
        [23.5580, 24.6262, 24.8039, 20.4629]])

In [48]:
some_tensor = some_tensor / 5
some_tensor

tensor([[4.9522, 4.0091, 4.0723, 4.0204],
        [4.5692, 4.5209, 4.2219, 4.9780],
        [4.7116, 4.9252, 4.9608, 4.0926]])

In [49]:
torch.mul(some_tensor, 2)

tensor([[9.9043, 8.0182, 8.1446, 8.0408],
        [9.1385, 9.0418, 8.4438, 9.9560],
        [9.4232, 9.8505, 9.9215, 8.1851]])

In [50]:
torch.add(some_tensor, 1)

tensor([[5.9522, 5.0091, 5.0723, 5.0204],
        [5.5692, 5.5209, 5.2219, 5.9780],
        [5.7116, 5.9252, 5.9608, 5.0926]])

## Matrix multiplicaiton

tow main ways of performing multiplicaton in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must mach:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [51]:
# element-wise multiplication
some_tensor * some_tensor

tensor([[24.5240, 16.0728, 16.5838, 16.1634],
        [20.8780, 20.4384, 17.8246, 24.7806],
        [22.1991, 24.2580, 24.6093, 16.7491]])

In [52]:
some_tensor1 = torch.rand(3,4)
some_tensor2 = torch.rand(4,3)

In [53]:
# matrix multiplication
torch.matmul(some_tensor1, some_tensor2)

tensor([[0.5543, 0.3823, 0.2606],
        [1.2326, 1.3165, 0.6791],
        [1.2332, 1.4209, 0.9870]])

In [54]:
tensor = torch.tensor([1, 2, 3])

In [55]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.03 ms, sys: 443 µs, total: 1.47 ms
Wall time: 1.23 ms


In [56]:
%%time 
torch.matmul(tensor, tensor)

CPU times: user 433 µs, sys: 187 µs, total: 620 µs
Wall time: 582 µs


tensor(14)

## one of the most common errors in deep learning: shape errors:

In [57]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_a, tensor_b) # torch.mm is the as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [58]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [59]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [60]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc(tensor aggregaion)

In [61]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
torch.min(x) # x.min()

tensor(1)

In [63]:
torch.max(x) # x.max()

tensor(91)

In [64]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [65]:
x.dtype

torch.int64

"torch.int64 is equals to torch.long"

In [66]:
x.mean(dtype=torch.float32) #torch.mean(x.type(torch.float32))

tensor(46.)

In [67]:
x.sum() # torch.sum(x)

tensor(460)

### finding the positional min and max

In [68]:
x.argmin() # returns index position of target tensor where the minimum value occurs

tensor(0)

In [69]:
x[0]

tensor(1)

In [70]:
x.argmax() # returns index position of target tensor where the maximum value occurs

tensor(9)

In [71]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) os side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* Permute - Return a view of the input with dimennsions permuted (swapped) in a certain way

In [72]:
# Let's create a tensor
x = torch.arange(1.0, 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [74]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
x_reshaped = x.reshape(2, 9)
x_reshaped, x_reshaped.shape

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [76]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [77]:
x = torch.arange(1.0, 11.)
x , x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [78]:
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [79]:
x = torch.arange(1, 10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [80]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [81]:
# changing z changes x (because a view of a tensor shares the same memory as the original input )
z[: ,0] = 5
z ,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [82]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [83]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked 

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [84]:
x_reshaped = x_reshaped.reshape(1, 10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [85]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [86]:
x_squeezed.shape

torch.Size([10])

In [87]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [88]:
x_unsqueezed.shape

torch.Size([1, 10])

In [89]:
# torch.permute - rearranges the timensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [اheight, width, colour_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'previous shape: { x_original.shape}')
print(f'previous shape: { x_permuted.shape}') # [colour_channels, height, width]

previous shape: torch.Size([224, 224, 3])
previous shape: torch.Size([3, 224, 224])


In [90]:
x_original

tensor([[[0.9452, 0.6567, 0.3052],
         [0.4494, 0.5172, 0.4935],
         [0.8873, 0.5144, 0.9885],
         ...,
         [0.9870, 0.7763, 0.7745],
         [0.1898, 0.9142, 0.9512],
         [0.5033, 0.4829, 0.7730]],

        [[0.4708, 0.1138, 0.6871],
         [0.7596, 0.4331, 0.0534],
         [0.3834, 0.8546, 0.3686],
         ...,
         [0.6968, 0.2672, 0.7443],
         [0.9589, 0.5831, 0.8937],
         [0.8953, 0.4913, 0.6038]],

        [[0.0758, 0.3348, 0.8879],
         [0.0925, 0.6748, 0.7462],
         [0.0941, 0.8616, 0.3273],
         ...,
         [0.7798, 0.3008, 0.7102],
         [0.2439, 0.9247, 0.1040],
         [0.6504, 0.8874, 0.7125]],

        ...,

        [[0.4605, 0.2659, 0.9222],
         [0.1997, 0.5817, 0.3401],
         [0.8814, 0.9362, 0.1417],
         ...,
         [0.0457, 0.5593, 0.8653],
         [0.8833, 0.5604, 0.9272],
         [0.8844, 0.0074, 0.8839]],

        [[0.6636, 0.1240, 0.4604],
         [0.6574, 0.5261, 0.5386],
         [0.

In [91]:
x_original[0, 0, :]

tensor([0.9452, 0.6567, 0.3052])

In [92]:
x_original[0, 0, 0]

tensor(0.9452)

In [93]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

## Indexing (selection data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [94]:
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [95]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
x[0][0]

tensor([1, 2, 3])

In [97]:
x[0][0][0]

tensor(1)

In [98]:
x[0][0][1]

tensor(2)

In [99]:
x[0][1][1]

tensor(5)

In [100]:
x[1][1][1]

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [101]:
# you can use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [102]:
# Get all values of 0th and 1st dimensions but only index 1 and 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [103]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [104]:
# Get index of 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [105]:
# index on x to return 9
x[0, 2, 2] # is equals to x[0][2][2]

tensor(9)

In [106]:
# index on x to return 3, 6, 9
x[0, :, 2]# is not equals to x[0][:][2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific python numerical computing library and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want to PyTorch tensor -> `torch.form_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [107]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy to pytorch
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [108]:
array.dtype

dtype('float64')

In [109]:
tensor.dtype # this isn't pytorch default type

torch.float64

In [112]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [114]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [116]:
tensor.dtype # tensor with default type from numpy

torch.float32

In [118]:
# change the value of array< what this will do to `tensor`?
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [121]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [122]:
# change the tensor, what happens to `numpy_tensor`?
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again -> ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [124]:
# Create two random tensors
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.6756, 0.4295, 0.9294, 0.0935],
        [0.7411, 0.7103, 0.2935, 0.1209],
        [0.8809, 0.2954, 0.4290, 0.6650]])
tensor([[0.4618, 0.7801, 0.9239, 0.9650],
        [0.8612, 0.5562, 0.0793, 0.2775],
        [0.6404, 0.3071, 0.5581, 0.1542]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [127]:
# Let's make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42 # whatever you want

torch.manual_seed(RANDOM_SEED)
random_tensor_a = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. Getting a GPU 

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires teh investment of purchasing a GPU, there's a lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allows you to rent computers on the cloud and access them 

for 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documenttion:https://pytorch.org/get-started/locally/    



### 2. Check for GPU access with PyTorch 

In [128]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU OR CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [129]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [130]:
torch.cuda.device_count() # the number of GPUs we have access

1

### 3. putting tensors (and models) on the GPU 

the reason we want our tensors/models on the GPU is because using a GPU results in faster computations. 

In [132]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [134]:
tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [135]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [136]:
# If tensors is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [137]:
# to fix the GPU tensor with NumPy issue, we can first set it to the CPU 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])