# Introduction to pytorch

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

2.1.1+cu121


In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[6, 7],
                       [8, 9]])


In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0]

tensor([6, 7])

In [13]:
MATRIX[1]

tensor([8, 9])

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [2, 4, 5]])

In [18]:
TENSOR[0][1]

tensor([3, 4, 5])

In [19]:
TENSOR[0][1][1]

tensor(4)

## Random tensor

In [20]:
random_tensor = torch.rand(3,4) 
random_tensor

tensor([[0.7179, 0.6202, 0.0962, 0.8833],
        [0.9544, 0.4867, 0.5807, 0.5960],
        [0.8985, 0.0176, 0.0659, 0.1783]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor = torch.rand(1, 10,10) 
random_tensor

tensor([[[0.8097, 0.0232, 0.4518, 0.3904, 0.0318, 0.7990, 0.1368, 0.1000,
          0.0448, 0.5974],
         [0.0252, 0.2983, 0.2615, 0.0359, 0.3243, 0.9807, 0.7110, 0.4803,
          0.3771, 0.0326],
         [0.2057, 0.3165, 0.4887, 0.3057, 0.2666, 0.5919, 0.3051, 0.8271,
          0.7801, 0.1111],
         [0.5744, 0.6620, 0.3666, 0.3929, 0.2375, 0.5105, 0.7774, 0.2712,
          0.1133, 0.4532],
         [0.0662, 0.2697, 0.8176, 0.3150, 0.3393, 0.5979, 0.5536, 0.3963,
          0.8725, 0.0769],
         [0.3894, 0.4839, 0.0789, 0.1090, 0.4611, 0.2998, 0.6642, 0.1659,
          0.6313, 0.3333],
         [0.9852, 0.1185, 0.1003, 0.7415, 0.3709, 0.4140, 0.9993, 0.8326,
          0.9079, 0.1355],
         [0.7911, 0.6249, 0.1579, 0.1103, 0.0048, 0.7945, 0.1124, 0.0399,
          0.7505, 0.1203],
         [0.1118, 0.1898, 0.4537, 0.5090, 0.7920, 0.7569, 0.1542, 0.0294,
          0.2334, 0.0266],
         [0.4849, 0.2594, 0.5897, 0.2108, 0.8460, 0.9589, 0.5041, 0.2691,
          0.6378,

In [23]:
random_tensor.ndim

3

In [24]:
# create a random tensor with similar shape of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor

tensor([[[0.3475, 0.7246, 0.0348],
         [0.7774, 0.3300, 0.3407],
         [0.6325, 0.4190, 0.4330],
         ...,
         [0.4742, 0.3265, 0.0131],
         [0.6156, 0.7915, 0.2592],
         [0.4476, 0.0686, 0.1692]],

        [[0.8393, 0.0999, 0.7017],
         [0.6411, 0.5936, 0.1273],
         [0.9032, 0.8705, 0.0639],
         ...,
         [0.5950, 0.1832, 0.9274],
         [0.6714, 0.2416, 0.3902],
         [0.4363, 0.9051, 0.9212]],

        [[0.8016, 0.9456, 0.5326],
         [0.3698, 0.2802, 0.2441],
         [0.3853, 0.9636, 0.5383],
         ...,
         [0.4484, 0.3314, 0.6202],
         [0.6659, 0.0366, 0.3224],
         [0.0643, 0.7715, 0.6647]],

        ...,

        [[0.9638, 0.2066, 0.6380],
         [0.9257, 0.8438, 0.9671],
         [0.6823, 0.9118, 0.7078],
         ...,
         [0.2902, 0.5942, 0.0426],
         [0.5499, 0.8884, 0.9305],
         [0.4472, 0.0249, 0.5736]],

        [[0.6327, 0.2057, 0.1109],
         [0.7013, 0.3025, 0.6706],
         [0.

In [25]:
random_image_size_tensor.shape

torch.Size([224, 224, 3])

In [26]:
random_image_size_tensor.ndim

3

### zeros and ones

In [27]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
onse = torch.ones(2, 3)
onse

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
onse.dtype

torch.float32

## creating a range of tensors and tensors-like

In [30]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
torch.arange(start=0, end=1000, step=77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [32]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**note:** tensor data types is one of the 3 big errors you'll run into with pytorch & deep learnig:
1. tensors not right data types
2. tensors not right shape
3. tensors not on the right device

In [33]:
torch.tensor([3.0, 6.0, 9.0]).dtype

torch.float32

In [34]:
torch.tensor([3.0, 6.0, 9.0], dtype=None).dtype

torch.float32

In [35]:
torch.tensor([3.0, 6.0, 9.0],
             dtype=None, # what data type is the tensor (float32 or float16)
             device=None, # what device is your tenosr on 
             requires_grad=False # whether or not to track gradients with this tensors operations 
            )

tensor([3., 6., 9.])

In [36]:
torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

## getting infromation about tenosrs (tensor attributes)
1. to get date type of a tensor, use `tensor.dtype`
2. to get shape from a tensor, use `tensor.shape`
3. to get device from a tensor, use `tensor.device`

In [37]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2772, 0.3614, 0.5920, 0.1667],
        [0.9165, 0.6012, 0.9175, 0.5433],
        [0.0115, 0.6464, 0.5345, 0.6229]])

In [38]:
print(some_tensor)
print(f"data type of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device tensor is on:{some_tensor.device}")

tensor([[0.2772, 0.3614, 0.5920, 0.1667],
        [0.9165, 0.6012, 0.9175, 0.5433],
        [0.0115, 0.6464, 0.5345, 0.6229]])
data type of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device tensor is on:cpu


In [39]:
some_tensor + 10

tensor([[10.2772, 10.3614, 10.5920, 10.1667],
        [10.9165, 10.6012, 10.9175, 10.5433],
        [10.0115, 10.6464, 10.5345, 10.6229]])

In [40]:
some_tensor ** 2

tensor([[7.6813e-02, 1.3058e-01, 3.5043e-01, 2.7790e-02],
        [8.3993e-01, 3.6148e-01, 8.4189e-01, 2.9521e-01],
        [1.3121e-04, 4.1784e-01, 2.8573e-01, 3.8802e-01]])

In [41]:
some_tensor / 10

tensor([[0.0277, 0.0361, 0.0592, 0.0167],
        [0.0916, 0.0601, 0.0918, 0.0543],
        [0.0011, 0.0646, 0.0535, 0.0623]])

In [42]:
8/3

2.6666666666666665

In [43]:
8//3

2

## manupaltin tesnors

tensors operatons include:
* Adding
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multipliciton

In [44]:
some_tensor = some_tensor + 5
some_tensor

tensor([[5.2772, 5.3614, 5.5920, 5.1667],
        [5.9165, 5.6012, 5.9175, 5.5433],
        [5.0115, 5.6464, 5.5345, 5.6229]])

In [45]:
some_tensor = some_tensor * 5
some_tensor

tensor([[26.3858, 26.8068, 27.9599, 25.8335],
        [29.5824, 28.0061, 29.5877, 27.7167],
        [25.0573, 28.2320, 27.6727, 28.1146]])

In [46]:
some_tensor = some_tensor - 5
some_tensor

tensor([[21.3858, 21.8068, 22.9599, 20.8335],
        [24.5824, 23.0061, 24.5877, 22.7167],
        [20.0573, 23.2320, 22.6727, 23.1146]])

In [47]:
some_tensor = some_tensor / 5
some_tensor

tensor([[4.2772, 4.3614, 4.5920, 4.1667],
        [4.9165, 4.6012, 4.9175, 4.5433],
        [4.0115, 4.6464, 4.5345, 4.6229]])

In [48]:
torch.mul(some_tensor, 2)

tensor([[8.5543, 8.7227, 9.1839, 8.3334],
        [9.8330, 9.2025, 9.8351, 9.0867],
        [8.0229, 9.2928, 9.0691, 9.2458]])

In [49]:
torch.add(some_tensor, 1)

tensor([[5.2772, 5.3614, 5.5920, 5.1667],
        [5.9165, 5.6012, 5.9175, 5.5433],
        [5.0115, 5.6464, 5.5345, 5.6229]])

## Matrix multiplicaiton

tow main ways of performing multiplicaton in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must mach:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [50]:
# element-wise multiplication
some_tensor * some_tensor

tensor([[18.2940, 19.0214, 21.0862, 17.3614],
        [24.1718, 21.1713, 24.1822, 20.6418],
        [16.0918, 21.5891, 20.5621, 21.3713]])

In [51]:
some_tensor1 = torch.rand(3,4)
some_tensor2 = torch.rand(4,3)

In [52]:
# matrix multiplication
torch.matmul(some_tensor1, some_tensor2)

tensor([[0.2793, 0.6696, 0.9283],
        [0.6126, 0.6411, 1.3438],
        [0.9080, 1.4834, 1.8188]])

In [53]:
tensor = torch.tensor([1, 2, 3])

In [54]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 0 ns, sys: 1.74 ms, total: 1.74 ms
Wall time: 28.6 ms


In [55]:
%%time 
torch.matmul(tensor, tensor)

CPU times: user 633 µs, sys: 296 µs, total: 929 µs
Wall time: 26 ms


tensor(14)

## one of the most common errors in deep learning: shape errors:

In [56]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_b = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_a, tensor_b) # torch.mm is the as torch.matmul (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [57]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [58]:
tensor_b.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [59]:
torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc(tensor aggregaion)

In [78]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [79]:
torch.min(x) # x.min()

tensor(1)

In [80]:
torch.max(x) # x.max()

tensor(91)

In [81]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [82]:
x.dtype

torch.int64

"torch.int64 is equals to torch.long"

In [83]:
x.mean(dtype=torch.float32) #torch.mean(x.type(torch.float32))

tensor(46.)

In [84]:
x.sum() # torch.sum(x)

tensor(460)

### finding the positional min and max

In [86]:
x.argmin() # returns index position of target tensor where the minimum value occurs

tensor(0)

In [87]:
x[0]

tensor(1)

In [88]:
x.argmax() # returns index position of target tensor where the maximum value occurs

tensor(9)

In [89]:
x[9]

tensor(91)